// <auto-generated />
namespace GgcmsCSharp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class 增加管理菜单属性 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(增加管理菜单属性));
        
        string IMigrationMetadata.Id
        {
            get { return "201705220610191_增加管理菜单属性"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
