// <auto-generated />
namespace GgcmsCSharp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class 修改友情链接类型LinkType为字符型 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(修改友情链接类型LinkType为字符型));
        
        string IMigrationMetadata.Id
        {
            get { return "201708300038156_修改友情链接类型LinkType为字符型"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
