// <auto-generated />
namespace GgcmsCSharp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class 分类中添加文章数统计 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(分类中添加文章数统计));
        
        string IMigrationMetadata.Id
        {
            get { return "201706290753311_分类中添加文章数统计"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
