// <auto-generated />
namespace GgcmsCSharp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class 广告表增加Image字段 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(广告表增加Image字段));
        
        string IMigrationMetadata.Id
        {
            get { return "201708291030174_广告表增加Image字段"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
