// <auto-generated />
namespace GgcmsCSharp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GgcmsCategoryaddRouteKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GgcmsCategoryaddRouteKey));
        
        string IMigrationMetadata.Id
        {
            get { return "201801290335440_GgcmsCategory-add-RouteKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
