// <auto-generated />
namespace GgcmsCSharp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addmodeulecolkey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmodeulecolkey));
        
        string IMigrationMetadata.Id
        {
            get { return "201908160040427_add-modeule-col-key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
